build fix
Pepperi-Addons/audit-data-log pull request #101
Opened 2024-11-05 14:51 UTC by izhar-ahmad-pepperi

2024-11-05 19:34 UTC, roiaharon-pepperi requested changes

2024-11-05 19:34 UTC, roiaharon-pepperi commented on server-side/tests.ts
> +        return new TestRunner(client as unknown as any, request).run(new Test());
this is not an accepted solution.. need to figure out why this is not happening on other addons that have tests..
if the versions doesn't match, than maybe need to upgrade the version.. 
please compare to a working addon (i.e your training addon), and see what need to be changed

2024-11-06 05:08 UTC, izhar-ahmad-pepperi commented on server-side/tests.ts
> +        return new TestRunner(client as unknown as any, request).run(new Test());
Updated the version.

2024-11-06 05:30 UTC, Manish-Josh-pepperi approved these changes

2024-11-06 05:45 UTC, merged