Separates addon block relation logic
Pepperi-Addons/audit-data-log pull request #102
Opened 2024-11-05 15:11 UTC by izhar-ahmad-pepperi

2024-11-05 19:38 UTC, roiaharon-pepperi requested changes

2024-11-05 19:38 UTC, roiaharon-pepperi commented on server-side/installation.ts
> +        if (request.body.FromVersion && Semver.compare(request.body.FromVersion, '1.3.0')) {
what does compare means? if it's true than it below this version or above? doesn't it returns a number?
why not use lte like on the other conditions?

2024-11-06 03:42 UTC, izhar-ahmad-pepperi commented on server-side/installation.ts
> +        if (request.body.FromVersion && Semver.compare(request.body.FromVersion, '1.3.0')) {
used Semver.gte.

2024-11-07 06:57 UTC, roiaharon-pepperi approved these changes

2024-11-07 06:57 UTC, roiaharon-pepperi commented on server-side/installation.ts
> +        if (request.body.FromVersion && Semver.gte(request.body.FromVersion, '1.3.0')) {
why gte? don't you want to check whether you're upgrading from version **before** 1.3.0? you need lte, not gte

2024-11-07 07:45 UTC, merged