#742791 check for empty field ID
Pepperi-Addons/audit-data-log pull request #106
Opened 2024-11-12 08:22 UTC by izhar-ahmad-pepperi

https://dev.azure.com/advantive-devops/Advantive/_workitems/edit/742791

2024-11-12 13:17 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +          Title: this.hostObject.FieldID ? `${this.translate.instant(this.hostObject.FieldID)} ${this.translate.instant('After')}` : '',
Empty Page will be shown

2024-11-12 14:35 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +          Title: this.hostObject.FieldID ? `${this.translate.instant(this.hostObject.FieldID)} ${this.translate.instant('After')}` : '',
What do you suggest, I discussed it with @tushar-pepperi  he agrees showing empty page.
We can return in API, that Field ID is mandatory if above solution is not ok.

2024-11-13 07:14 UTC, roiaharon-pepperi requested changes

2024-11-13 07:14 UTC, roiaharon-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +          Title: this.hostObject.FieldID ? `${this.translate.instant(this.hostObject.FieldID)} ${this.translate.instant('After')}` : '',
I think that empty page is not very clear because the user is not aware of why there are no changes..
there should be an error message telling that there are mandatory fields that weren't supplied..
now we're talking about the fieldID, but it's related to every mandatory field

2024-11-13 11:40 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +          Title: this.hostObject.FieldID ? `${this.translate.instant(this.hostObject.FieldID)} ${this.translate.instant('After')}` : '',
@roiaharon-pepperi  Added validations in API

2024-11-13 12:33 UTC, roiaharon-pepperi requested changes

2024-11-13 12:33 UTC, roiaharon-pepperi commented on server-side/api.ts
>          let where: string[] = request.query.where ? request.query.where.split(" and ") : [];
what if the where clause will not contain and? what if it will contain only or?

2024-11-13 12:33 UTC, roiaharon-pepperi commented on server-side/utilities.service.ts
> +            throw new Error("field_id is required");
this is not the name of the property on the hostObject.. this should match there

2024-11-13 12:54 UTC, izhar-ahmad-pepperi commented on server-side/api.ts
>          let where: string[] = request.query.where ? request.query.where.split(" and ") : [];
If it doesn't contains end that means only 1 property/condition is provided. For "or" condition there is no handling anywhere in audit log, In our code our core elastic search queries are only based on must, which is logically and.

2024-11-13 12:54 UTC, izhar-ahmad-pepperi commented on server-side/utilities.service.ts
> +            throw new Error("field_id is required");
Done

2024-11-14 07:04 UTC, roiaharon-pepperi approved these changes

2024-11-14 07:04 UTC, merged