Di 28703 property audit log abi
Pepperi-Addons/audit-data-log pull request #97
Opened 2024-10-04 06:44 UTC by izhar-ahmad-pepperi

1. [DI-28703] Implement PropertyAuditLog ABI.
2. [DI-28694] expose property changes endpoint.

[DI-28703]: https://dev.azure.com/advantive-devops/Advantive/_workitems/edit/675452
[DI-28694]: https://dev.azure.com/advantive-devops/Advantive/_workitems/edit/675449

2024-10-13 09:14 UTC, roiaharon-pepperi requested changes

2024-10-14 04:40 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +import { UpdatedField, Document } from '../../../../../shared/models/document';
In Audit data logs add-on , shared is already created as separate folder instead of different package.

2024-10-14 05:08 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +        this.convertToPepRowData(doc, userKeys)
https://github.com/Pepperi-Addons/ngx-lib/blob/master/projects/ngx-lib-tester/src/app/list-example/list-example.component.ts

I have taken a reference from above example from ngx-lib.

2024-10-14 05:11 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.scss
> +.field-log-list {
Its a pep list, and we need styling for updated fields display, for example when we have json string in updated field value.
<img width="1502" alt="Screenshot 2024-10-14 at 10 40 36 AM" src="https://github.com/user-attachments/assets/d92cc15a-2630-4f98-98f5-3c8b3691aa8c">

2024-10-14 17:52 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.scss
> +.field-log-list {
https://github.com/Pepperi-Addons/ngx-lib/blob/master/projects/ngx-lib-tester/src/app/list-example/list-example.component.html
Its from ngx-lib, provide more ways to format and customize our view.

2024-10-16 11:38 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.scss
> +.field-log-list {
@roiaharon-pepperi  Updated pep-list to pep-generic-list.

2024-10-16 11:38 UTC, izhar-ahmad-pepperi commented on client-side/src/app/components/audit-data-field-log-block/audit-data-field-log-block.component.ts
> +        this.convertToPepRowData(doc, userKeys)
pep-generic-list added , removed pep-list

2024-10-27 12:04 UTC, roiaharon-pepperi approved these changes

2024-10-27 12:05 UTC, merged