Di 28704 status history
Pepperi-Addons/audit-data-log pull request #98
Opened 2024-10-12 10:51 UTC by izhar-ahmad-pepperi

2024-10-13 11:06 UTC, roiaharon-pepperi requested changes

2024-10-13 11:06 UTC, roiaharon-pepperi commented on server-side/utilities.service.ts
> +        return s[0].toUpperCase() + s.slice(1);
why do you need this function?

2024-10-13 11:06 UTC, roiaharon-pepperi commented on shared/models/document.ts
> +export interface UpsertResponseObject {
isn't this interface already exist on papi-sdk?

2024-10-14 05:53 UTC, izhar-ahmad-pepperi commented on server-side/utilities.service.ts
> +        return s[0].toUpperCase() + s.slice(1);
Status of objects is returned in small case from elastic search. For capitalizing the first letter we have to create this.

2024-10-14 05:55 UTC, izhar-ahmad-pepperi commented on shared/models/document.ts
> +export interface UpsertResponseObject {
I don't think so, taking reference from Data Index.
https://github.com/Pepperi-Addons/Data-Index/blob/3c9802b95cab6da49fea68d8e528b22b633a38f0/server-side/base-index.ts#L818-L819

2024-10-14 06:37 UTC, izhar-ahmad-pepperi commented on server-side/api.ts
> +            AddonUUID: client.AddonUUID,
By what name this key will exist in client header?
@roiaharon-pepperi

2024-10-14 07:28 UTC, izhar-ahmad-pepperi commented on server-side/api.ts
> +        bulkBodyNDJSON += JSON.stringify({ "index": { "_index": Constants.AUDIT_DATA_LOG_INDEX, _id: object['_id'], "_type": "_doc" } }) + os.EOL;
done

2024-10-14 07:28 UTC, izhar-ahmad-pepperi commented on server-side/api.ts
> +            AddonUUID: client.AddonUUID,
done

2024-10-14 07:29 UTC, izhar-ahmad-pepperi commented on server-side/api.ts
> +                    Key: matchingObject.ObjectKey,
done

2024-10-14 07:29 UTC, izhar-ahmad-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
> +                    expect(response[0].Key).to.equal("98a7a422-a0a7-4333-9c30-67bca8f3ea4d");
done

2024-10-14 07:29 UTC, izhar-ahmad-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
done

2024-10-14 07:29 UTC, izhar-ahmad-pepperi commented on server-side/utilities.service.ts
> +        if (client.AddonUUID !== ownerUUID) {
removed this check.

2024-10-14 07:29 UTC, izhar-ahmad-pepperi commented on server-side/utilities.service.ts
> +                Key: object.ObjectKey,
done

2024-10-16 11:51 UTC, izhar-ahmad-pepperi commented on server-side/data-retrieval.service.ts
> +        const ownerId = ownerUUID ? ownerUUID : config.AddonUUID;
The is only an API call used at other places also, we are already throwing error in our case here 
https://github.com/Pepperi-Addons/audit-data-log/blob/41608c0ed64ff3194eead90aaad173c090b18fd0/server-side/utilities.service.ts#L14

2024-10-17 06:12 UTC, izhar-ahmad-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
> +import sinon from 'sinon';
Removed sinon package and implement custom mock.

2024-10-27 12:09 UTC, roiaharon-pepperi requested changes

2024-10-27 12:09 UTC, roiaharon-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
I'm not sure why do you need all the mocking? what not use the original implementation and change the data.. this is the correct way to test your code..

2024-10-28 05:22 UTC, izhar-ahmad-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
The idea behind using mock data is, we need some payload to test the upsert of data and for validations.

2024-10-28 05:28 UTC, izhar-ahmad-pepperi commented on server-side/integration-tests/audit-data-log.tests.ts
Also, validate owner, external call needs to be tested in various different scenarios which requires to simulate different headers setup.
We are testing our actual API of bulk upsert using real time api, only the external call is mocked.

2024-10-30 07:39 UTC, roiaharon-pepperi requested changes

2024-11-04 08:06 UTC, roiaharon-pepperi approved these changes

2024-11-04 08:06 UTC, merged